### ISSUE TITLE
Consider @grpc/grpc-js

### ISSUE THREAD

**Issue by tatemz** [redhoyasa/grpc-reflection-js#2]
Hey. This is a cool library!

I was recently trying to integrate this into https://github.com/Urigo/graphql-mesh/pull/1086 and had some conflicts when passing `@grpc/grpc-js` `CredentialsChannel` to your `Client` constructor. See the relevant comment in https://github.com/Urigo/graphql-mesh/pull/1086

> There is a conflict when using `grpc-reflection-js`. The `CredentialsChannel` type used by it is different than the `CredentialsChannel` type used by `@grpc/grpc-js`. This is why I swapped in `grpc`. However, on the `grpc` package README, it states that this package is deprecated (presumably in favor of `@grpc/grpc-node`? :thinking: :man_shrugging:)
I find this odd, because when using the JS `protoc` plugin, all of the generated gRPC server/client code uses the `grpc` package.
I suppose until `protoc` updates it's output dependency, then using `grpc` should be ok. Alternatively, we can submit a PR to `grpc-reflection-js` to update that dependency to use `@grpc/grpc-js`. Whew :sweat_smile:

**Comment by redhoyasa** [comment]
Hey, thanks for your interest.

I have reviewed your [changes](https://github.com/Urigo/graphql-mesh/pull/1086). Originally, I was using `grpc` because I want to create some changes to [uw-labs/bloomrpc](https://github.com/uw-labs/bloomrpc).

I think we can migrate to `@grpc/grpc-js` since protoc also supports `@grpc/grpc-js` (see [this](https://github.com/agreatfool/grpc_tools_node_protoc_ts) for the detail).

But I will not available in a few weeks. If you're in hurry, don't hesitate to create PR for this.

**Comment by redhoyasa** [comment]
Hey @tatemz, I just published your changes in version 0.0.7

**Comment by tatemz** [comment]
:100:  Awesome!

Are the release/tagged versions in git synchronized with the versions in the NPM registry?

**Comment by redhoyasa** [comment]
Not yet, I was getting problems when publishing changes to NPM registry via Github Action and ended up making many unused tags and releases. Will fix it someday later.

**Comment by redhoyasa** [comment]
I just made them synchronized.
